/**
 * `@ce-net/cap` — CE's capability primitive in pure TypeScript.
 *
 * This is a byte-exact port of the Rust `ce-cap` crate: the same bincode-1 preimage, the same
 * `sha256` content-address, the same Ed25519 signatures, and the same attenuating-chain
 * verification algorithm. A capability minted here verifies on a Rust node and vice versa; the
 * golden-vector test (`test/golden.test.ts`) pins this guarantee against vectors generated by
 * `cargo run -p ce-cap --example gen_vectors`.
 *
 * Runtime-agnostic: depends only on `@noble/ed25519` and `@noble/hashes` (no Node built-ins beyond
 * `TextEncoder`/`TextDecoder`, which are global in Node 20+, Deno, Bun, and browsers).
 */

import { ed25519 } from "@noble/ed25519";
import { sha256 } from "@noble/hashes/sha256";
import {
  BincodeReader,
  BincodeWriter,
  fromHex,
  toHex,
} from "./bincode.js";
import type {
  Capability,
  CapId,
  Caveats,
  NodeId,
  Resource,
  SignedCapability,
} from "./types.js";

export {
  BincodeReader,
  BincodeWriter,
  fromHex,
  toHex,
} from "./bincode.js";
export type {
  Capability,
  CapId,
  Caveats,
  NodeId,
  Resource,
  SignedCapability,
} from "./types.js";
export { defaultCaveats } from "./types.js";

/**
 * Domain-separation tag mixed into every capability signature, matching `CAP_DOMAIN` in Rust. It is
 * written with `serialize_bytes` (u64 length prefix), exactly as Rust serializes the leading
 * `&[u8]` tuple element.
 */
const CAP_DOMAIN: Uint8Array = new TextEncoder().encode("ce-cap-v1");

/** Resource enum variant indices — must match the Rust `enum Resource` declaration order. */
const RESOURCE_TAG = { any: 0, node: 1, tag: 2, allOf: 3 } as const;

// ---------------------------------------------------------------------------
// Keys
// ---------------------------------------------------------------------------

/** An Ed25519 keypair. `nodeId` is the 32-byte public key; `secret` is the 32-byte seed. */
export interface Keypair {
  secret: Uint8Array;
  nodeId: NodeId;
}

/** Derive the deterministic keypair for a given 32-byte secret seed. */
export async function keypairFromSecret(secret: Uint8Array): Promise<Keypair> {
  if (secret.length !== 32) throw new Error("secret seed must be 32 bytes");
  const nodeId = await ed25519.getPublicKeyAsync(secret);
  return { secret: Uint8Array.from(secret), nodeId };
}

/** Generate a fresh random keypair (uses `@noble/ed25519`'s CSPRNG). */
export async function generateKeypair(): Promise<Keypair> {
  // `randomSecretKey` is the @noble/ed25519 v2 name; tolerate the older `randomPrivateKey` alias.
  const utils = ed25519.utils as {
    randomSecretKey?: () => Uint8Array;
    randomPrivateKey?: () => Uint8Array;
  };
  const gen = utils.randomSecretKey ?? utils.randomPrivateKey;
  if (!gen) throw new Error("@noble/ed25519: no random secret-key generator available");
  return keypairFromSecret(gen());
}

// ---------------------------------------------------------------------------
// bincode encoding of capability sub-structures
// ---------------------------------------------------------------------------

function encodeResource(w: BincodeWriter, r: Resource): void {
  switch (r.kind) {
    case "any":
      w.writeEnumTag(RESOURCE_TAG.any);
      break;
    case "node":
      w.writeEnumTag(RESOURCE_TAG.node);
      assertLen(r.node, 32, "Resource::Node id");
      w.writeFixedBytes(r.node);
      break;
    case "tag":
      w.writeEnumTag(RESOURCE_TAG.tag);
      w.writeString(r.tag);
      break;
    case "allOf":
      w.writeEnumTag(RESOURCE_TAG.allOf);
      w.writeU64(BigInt(r.tags.length));
      for (const t of r.tags) w.writeString(t);
      break;
  }
}

function decodeResource(rd: BincodeReader): Resource {
  const tag = rd.readEnumTag();
  switch (tag) {
    case RESOURCE_TAG.any:
      return { kind: "any" };
    case RESOURCE_TAG.node:
      return { kind: "node", node: rd.readFixedBytes(32) };
    case RESOURCE_TAG.tag:
      return { kind: "tag", tag: rd.readString() };
    case RESOURCE_TAG.allOf: {
      const n = Number(rd.readU64());
      const tags: string[] = [];
      for (let i = 0; i < n; i++) tags.push(rd.readString());
      return { kind: "allOf", tags };
    }
    default:
      throw new Error(`invalid Resource variant tag ${tag}`);
  }
}

function encodeCaveats(w: BincodeWriter, c: Caveats): void {
  // Field order MUST match the Rust struct: not_before, not_after, max_cpu, max_mem_mb,
  // max_credits, allowed_ports, path_prefix.
  w.writeU64(c.not_before);
  w.writeU64(c.not_after);
  writeOptionU32(w, c.max_cpu);
  writeOptionU32(w, c.max_mem_mb);
  writeOptionU64(w, c.max_credits);
  // Option<Vec<u16>>
  if (c.allowed_ports === null) {
    w.writeOptionTag(false);
  } else {
    w.writeOptionTag(true);
    w.writeU64(BigInt(c.allowed_ports.length));
    for (const p of c.allowed_ports) w.writeU16(p);
  }
  // Option<String>
  if (c.path_prefix === null) {
    w.writeOptionTag(false);
  } else {
    w.writeOptionTag(true);
    w.writeString(c.path_prefix);
  }
}

function decodeCaveats(rd: BincodeReader): Caveats {
  const not_before = rd.readU64();
  const not_after = rd.readU64();
  const max_cpu = readOptionU32(rd);
  const max_mem_mb = readOptionU32(rd);
  const max_credits = readOptionU64(rd);
  let allowed_ports: number[] | null = null;
  if (rd.readOptionTag()) {
    const n = Number(rd.readU64());
    allowed_ports = [];
    for (let i = 0; i < n; i++) allowed_ports.push(rd.readU16());
  }
  let path_prefix: string | null = null;
  if (rd.readOptionTag()) path_prefix = rd.readString();
  return { not_before, not_after, max_cpu, max_mem_mb, max_credits, allowed_ports, path_prefix };
}

function writeOptionU32(w: BincodeWriter, v: number | null): void {
  if (v === null) {
    w.writeOptionTag(false);
  } else {
    w.writeOptionTag(true);
    w.writeU32(v);
  }
}

function writeOptionU64(w: BincodeWriter, v: bigint | null): void {
  if (v === null) {
    w.writeOptionTag(false);
  } else {
    w.writeOptionTag(true);
    w.writeU64(v);
  }
}

function readOptionU32(rd: BincodeReader): number | null {
  return rd.readOptionTag() ? rd.readU32() : null;
}

function readOptionU64(rd: BincodeReader): bigint | null {
  return rd.readOptionTag() ? rd.readU64() : null;
}

// ---------------------------------------------------------------------------
// cap_bytes / cap_id
// ---------------------------------------------------------------------------

/**
 * The canonical, domain-separated preimage the issuer signs. Byte-identical to Rust `cap_bytes`:
 * `bincode(( b"ce-cap-v1", issuer, audience, abilities, resource, caveats, nonce, parent ))`.
 *
 * The leading domain tag is a `&[u8]` -> `serialize_bytes` (u64 length prefix); `issuer`/`audience`
 * are fixed `[u8;32]` (no prefix); `abilities` is a `Vec<String>` (u64 count, then each String);
 * `nonce` is a u64; `parent` is `Option<[u8;32]>` (1-byte tag, then 32 raw bytes if `Some`).
 */
export function capBytes(c: Capability): Uint8Array {
  const w = new BincodeWriter();
  // Tuple element 0: the domain tag, as serialize_bytes.
  w.writeBytes(CAP_DOMAIN);
  // 1: issuer [u8;32]
  assertLen(c.issuer, 32, "issuer");
  w.writeFixedBytes(c.issuer);
  // 2: audience [u8;32]
  assertLen(c.audience, 32, "audience");
  w.writeFixedBytes(c.audience);
  // 3: abilities Vec<String>
  w.writeU64(BigInt(c.abilities.length));
  for (const a of c.abilities) w.writeString(a);
  // 4: resource enum
  encodeResource(w, c.resource);
  // 5: caveats struct
  encodeCaveats(w, c.caveats);
  // 6: nonce u64
  w.writeU64(c.nonce);
  // 7: parent Option<[u8;32]>
  if (c.parent === null) {
    w.writeOptionTag(false);
  } else {
    w.writeOptionTag(true);
    assertLen(c.parent, 32, "parent");
    w.writeFixedBytes(c.parent);
  }
  return w.finish();
}

/** The content-address of a capability — `sha256(capBytes(c))`. Matches Rust `cap_id`. */
export function capId(c: Capability): CapId {
  return sha256(capBytes(c));
}

// ---------------------------------------------------------------------------
// Signing / verification
// ---------------------------------------------------------------------------

/** Sign a capability body with the issuer's secret seed, yielding a `SignedCapability`. */
export async function signCapability(
  secret: Uint8Array,
  cap: Capability,
): Promise<SignedCapability> {
  if (secret.length !== 32) throw new Error("secret seed must be 32 bytes");
  const sig = await ed25519.signAsync(capBytes(cap), secret);
  return { cap, sig };
}

/** Build and sign a capability in one call (the TS analog of Rust `SignedCapability::issue`). */
export async function issue(
  issuerSecret: Uint8Array,
  issuer: NodeId,
  audience: NodeId,
  abilities: string[],
  resource: Resource,
  caveats: Caveats,
  nonce: bigint,
  parent: CapId | null,
): Promise<SignedCapability> {
  const cap: Capability = { issuer, audience, abilities, resource, caveats, nonce, parent };
  return signCapability(issuerSecret, cap);
}

/** Verify a single link's signature against its issuer key. */
export async function verifySig(link: SignedCapability): Promise<boolean> {
  try {
    return await ed25519.verifyAsync(link.sig, capBytes(link.cap), link.cap.issuer);
  } catch {
    return false;
  }
}

// ---------------------------------------------------------------------------
// Chain encode/decode (bincode Vec<SignedCapability> -> hex)
// ---------------------------------------------------------------------------

function encodeSignedCapability(w: BincodeWriter, sc: SignedCapability): void {
  // SignedCapability is a struct { cap, sig } — its fields concatenated. `cap` re-serializes via
  // the SAME field layout used inside cap_bytes EXCEPT without the leading domain tag (the domain
  // tag is only part of the signed preimage, not the stored Capability struct).
  encodeCapabilityStruct(w, sc.cap);
  // sig: [u8;64] uses serde_bytes (serialize_bytes) -> u64 length prefix + 64 bytes.
  assertLen(sc.sig, 64, "signature");
  w.writeBytes(sc.sig);
}

/** Encode the bare `Capability` struct (no domain tag) for the on-wire `SignedCapability`. */
function encodeCapabilityStruct(w: BincodeWriter, c: Capability): void {
  assertLen(c.issuer, 32, "issuer");
  w.writeFixedBytes(c.issuer);
  assertLen(c.audience, 32, "audience");
  w.writeFixedBytes(c.audience);
  w.writeU64(BigInt(c.abilities.length));
  for (const a of c.abilities) w.writeString(a);
  encodeResource(w, c.resource);
  encodeCaveats(w, c.caveats);
  w.writeU64(c.nonce);
  if (c.parent === null) {
    w.writeOptionTag(false);
  } else {
    w.writeOptionTag(true);
    assertLen(c.parent, 32, "parent");
    w.writeFixedBytes(c.parent);
  }
}

function decodeCapabilityStruct(rd: BincodeReader): Capability {
  const issuer = rd.readFixedBytes(32);
  const audience = rd.readFixedBytes(32);
  const nAbil = Number(rd.readU64());
  const abilities: string[] = [];
  for (let i = 0; i < nAbil; i++) abilities.push(rd.readString());
  const resource = decodeResource(rd);
  const caveats = decodeCaveats(rd);
  const nonce = rd.readU64();
  const parent = rd.readOptionTag() ? rd.readFixedBytes(32) : null;
  return { issuer, audience, abilities, resource, caveats, nonce, parent };
}

function decodeSignedCapability(rd: BincodeReader): SignedCapability {
  const cap = decodeCapabilityStruct(rd);
  const sig = rd.readBytes();
  if (sig.length !== 64) throw new Error("signature is not 64 bytes");
  return { cap, sig };
}

/** Encode a root-first chain to bincode bytes (matches Rust `encode_chain_bytes`). */
export function encodeChainBytes(chain: SignedCapability[]): Uint8Array {
  const w = new BincodeWriter();
  w.writeU64(BigInt(chain.length));
  for (const link of chain) encodeSignedCapability(w, link);
  return w.finish();
}

/** Decode a bincode chain (matches Rust `decode_chain_bytes`). */
export function decodeChainBytes(bytes: Uint8Array): SignedCapability[] {
  const rd = new BincodeReader(bytes);
  const n = Number(rd.readU64());
  const chain: SignedCapability[] = [];
  for (let i = 0; i < n; i++) chain.push(decodeSignedCapability(rd));
  if (!rd.done) throw new Error("trailing bytes after capability chain");
  return chain;
}

/** Encode a root-first chain to a hex token (matches Rust `encode_chain`). */
export function encodeChain(chain: SignedCapability[]): string {
  return toHex(encodeChainBytes(chain));
}

/** Decode a hex token produced by {@link encodeChain} (matches Rust `decode_chain`). */
export function decodeChain(token: string): SignedCapability[] {
  return decodeChainBytes(fromHex(token));
}

// ---------------------------------------------------------------------------
// Verification (port of Rust `authorize`)
// ---------------------------------------------------------------------------

/** Result of {@link verifyChain}: either authorized, or denied with a human-readable reason. */
export type AuthorizeResult = { ok: true } | { ok: false; reason: string };

/** Inputs for {@link verifyChain}, mirroring the parameters of Rust `authorize`. */
export interface AuthorizeParams {
  /** This node's own id (always an implicit accepted root). */
  selfId: NodeId;
  /** Additional configured root keys this node honors. */
  acceptedRoots: NodeId[];
  /** This node's self-tags, matched by `Resource::Tag`/`AllOf`. */
  selfTags: string[];
  /** Current unix time (seconds) for temporal caveats. */
  now: bigint;
  /** The principal presenting the chain — must equal the leaf's audience. */
  requester: NodeId;
  /** The opaque action string being authorized. */
  action: string;
  /** The presented chain, root-first. */
  chain: SignedCapability[];
  /** Consults on-chain revocation by `(issuer, nonce)`; default: nothing revoked. */
  isRevoked?: (issuer: NodeId, nonce: bigint) => boolean;
}

function eqBytes(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
  return true;
}

/** `Resource.matches` — does node (id, tags) fall within this resource set? Port of Rust. */
export function resourceMatches(r: Resource, id: NodeId, tags: string[]): boolean {
  switch (r.kind) {
    case "any":
      return true;
    case "node":
      return eqBytes(r.node, id);
    case "tag":
      return tags.includes(r.tag);
    case "allOf":
      return r.tags.every((t) => tags.includes(t));
  }
}

/** `Resource.is_subset_of` — is `self` no broader than `parent`? Port of Rust. */
export function resourceIsSubsetOf(self: Resource, parent: Resource): boolean {
  switch (parent.kind) {
    case "any":
      return true;
    case "node":
      return self.kind === "node" && eqBytes(self.node, parent.node);
    case "tag":
      if (self.kind === "tag") return self.tag === parent.tag;
      if (self.kind === "allOf") return self.tags.includes(parent.tag);
      return false;
    case "allOf":
      if (self.kind === "allOf") return parent.tags.every((p) => self.tags.includes(p));
      if (self.kind === "tag") return parent.tags.every((p) => p === self.tag);
      return false;
  }
}

/** Path containment on a `/` boundary — port of Rust `path_within`. */
function pathWithin(child: string, parent: string): boolean {
  const c = child.replace(/\/+$/, "");
  const p = parent.replace(/\/+$/, "");
  return p === "" || c === p || c.startsWith(`${p}/`);
}

function leOptNum(child: number | null, parent: number | null): boolean {
  if (parent === null) return true;
  if (child === null) return false;
  return child <= parent;
}

function leOptBig(child: bigint | null, parent: bigint | null): boolean {
  if (parent === null) return true;
  if (child === null) return false;
  return child <= parent;
}

/** `Caveats.valid_at` — are temporal caveats satisfied at `now`? Port of Rust. */
export function caveatsValidAt(c: Caveats, now: bigint): string | null {
  if (c.not_before !== 0n && now < c.not_before) return "capability not yet valid";
  if (c.not_after !== 0n && now > c.not_after) return "capability has expired";
  return null;
}

/** `Caveats.is_narrower_or_equal` — may a child only narrow the parent? Port of Rust. */
export function caveatsNarrowerOrEqual(self: Caveats, parent: Caveats): boolean {
  if (parent.not_after !== 0n && (self.not_after === 0n || self.not_after > parent.not_after)) {
    return false;
  }
  if (self.not_before < parent.not_before) return false;
  if (
    !leOptNum(self.max_cpu, parent.max_cpu) ||
    !leOptNum(self.max_mem_mb, parent.max_mem_mb) ||
    !leOptBig(self.max_credits, parent.max_credits)
  ) {
    return false;
  }
  if (parent.allowed_ports !== null) {
    if (self.allowed_ports === null) return false;
    if (!self.allowed_ports.every((p) => parent.allowed_ports!.includes(p))) return false;
  }
  if (parent.path_prefix !== null) {
    if (self.path_prefix === null) return false;
    if (!pathWithin(self.path_prefix, parent.path_prefix)) return false;
  }
  return true;
}

function abilitiesSubset(child: string[], parent: string[]): boolean {
  return child.every((a) => parent.includes(a));
}

/**
 * Decide whether `requester` may perform `action` on this node, given a presented chain. A faithful
 * port of Rust `authorize`, enforcing the same seven properties in the same order. Async because
 * Ed25519 verification is async in `@noble/ed25519`.
 */
export async function verifyChain(params: AuthorizeParams): Promise<AuthorizeResult> {
  const {
    selfId,
    acceptedRoots,
    selfTags,
    now,
    requester,
    action,
    chain,
    isRevoked = () => false,
  } = params;

  if (chain.length === 0) return deny("no capability presented");

  // 1. Root must be an accepted authority for this node.
  const rootIssuer = chain[0]!.cap.issuer;
  const rootAccepted = eqBytes(rootIssuer, selfId) || acceptedRoots.some((r) => eqBytes(r, rootIssuer));
  if (!rootAccepted) return deny("capability chain does not root at an accepted authority");

  for (let i = 0; i < chain.length; i++) {
    const link = chain[i]!;
    const c = link.cap;

    // 2. Signature.
    if (!(await verifySig(link))) return deny(`link ${i}: invalid signature`);
    // 3a. Temporal.
    const temporal = caveatsValidAt(c.caveats, now);
    if (temporal !== null) return deny(`link ${i}: ${temporal}`);
    // 3b. Revocation.
    if (isRevoked(c.issuer, c.nonce)) return deny(`link ${i}: capability revoked`);
    // 4. Resource must apply to this node.
    if (!resourceMatches(c.resource, selfId, selfTags)) {
      return deny(`link ${i}: resource does not match this node`);
    }

    if (i === 0) {
      // Root link carries no parent.
      if (c.parent !== null) return deny("root capability must not name a parent");
    } else {
      const parent = chain[i - 1]!.cap;
      // 5. Continuity.
      if (!eqBytes(c.issuer, parent.audience)) {
        return deny(`link ${i}: issuer is not the parent's audience`);
      }
      const expectedParentId = capId(parent);
      if (c.parent === null || !eqBytes(c.parent, expectedParentId)) {
        return deny(`link ${i}: parent hash does not match the chain`);
      }
      // 6. Attenuation.
      if (!abilitiesSubset(c.abilities, parent.abilities)) {
        return deny(`link ${i}: abilities exceed the parent`);
      }
      if (!resourceIsSubsetOf(c.resource, parent.resource)) {
        return deny(`link ${i}: resource is broader than the parent`);
      }
      if (!caveatsNarrowerOrEqual(c.caveats, parent.caveats)) {
        return deny(`link ${i}: caveats are broader than the parent`);
      }
    }
  }

  // 7. The leaf must be held by the requester and grant the action.
  const leaf = chain[chain.length - 1]!.cap;
  if (!eqBytes(leaf.audience, requester)) {
    return deny("leaf capability is not held by the request sender");
  }
  if (!leaf.abilities.includes(action)) {
    return deny(`capability does not grant '${action}'`);
  }
  return { ok: true };
}

function deny(reason: string): AuthorizeResult {
  return { ok: false, reason };
}

function assertLen(b: Uint8Array, n: number, what: string): void {
  if (b.length !== n) throw new Error(`${what} must be ${n} bytes, got ${b.length}`);
}
